name: Server checker

#on:
#  schedule:
#    - cron: '0 * * * *'
on: #push
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send API Request
        run: curl -X GET https://dbend.areso.pro/tos

      - name: Check Response Code
        id: check_response
#        run: echo "::set-output name=code::$(curl -s -o /dev/null -w "%{http_code}" https://dbend.areso.pro/tos)"
        run: echo "RESPONSE=$(curl -s -o /dev/null -w '%{http_code}' https://dbend.areso.pro/tos)" >> "$GITHUB_OUTPUT"

      - name: Response
        env:
          RESPONSE: ${{ steps.check_response.outputs.RESPONSE }}
        run: echo "The selected color is $RESPONSE"

#      - name: Set color
#        id: color-selector
#        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
#      - name: Get color
#        env:
#          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
#        run: echo "The selected color is $SELECTED_COLOR"


      - name: Handle Response 500
        uses: "appleboy/telegram-action@master"
        if: steps.check_response.outputs.code == 500
        with:
          to: ${{secrets.CHAT_ID}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          args: Server crashed!!!
        continue-on-error: true

      - name: Handle Response 502
        uses: "appleboy/telegram-action@master"
        if: steps.check_response.outputs.code == 502
        with:
          to: ${{secrets.CHAT_ID}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          args: Server crashed!!!
        continue-on-error: true


